package io.appery.apperyunit;

import java.awt.Dimension;
import javax.swing.BoxLayout;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.text.DefaultCaret;
import javax.swing.tree.TreeSelectionModel;

/**
 * Main application frame.
 */
public class DashboardFrame extends javax.swing.JFrame {

    ApperyService appery = new ApperyService();
            
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Utils.setIcon(this);
                
        DefaultCaret caret = (DefaultCaret)consoleArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        appery.init(this);
    }

    void createDashboard() {
        appery.loadScriptList();
        appery.loadFolders();
        appery.loadJsonDependencies();
        appery.ensureFixturesFolder();
        //depsPanel.setLayout(new GridLayout(0, 1));
        depsScroll.setPreferredSize(new Dimension(200,200));
        depsPanel.setLayout(new BoxLayout(depsPanel, BoxLayout.Y_AXIS));
        appery.buildDependenciesPanel(depsPanel);
        appery.printStats();
        
        scriptNameLabel.setText("<html><b>ApperyUnit</b> Version " + Utils.apperyUnitVersion + "</html>");
        appery.checkApperyUnitVersion();
                
        scriptsTree.setModel(appery.buildTree());
        scriptsTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        scriptsTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent e) {
                appery.treeNodeSelected(e);
            }
        });
        
        appery.buildParamList();
        //setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scriptsTree = new javax.swing.JTree();
        controlPanel = new javax.swing.JPanel();
        paramsPanel = new javax.swing.JPanel();
        saveParamsButton = new javax.swing.JButton();
        paramListComboBox = new javax.swing.JComboBox<>();
        newParamsButton = new javax.swing.JButton();
        resetParamsButton = new javax.swing.JButton();
        paramsSplitPane = new javax.swing.JSplitPane();
        paramsQueryScrollPane = new javax.swing.JScrollPane();
        paramsQueryArea = new javax.swing.JTextArea();
        paramsBodyScrollPane = new javax.swing.JScrollPane();
        paramsBodyArea = new javax.swing.JTextArea();
        scriptNamePanel = new javax.swing.JPanel();
        scriptNameLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        runButton = new javax.swing.JButton();
        echoButton = new javax.swing.JButton();
        testButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        dependenciesPanel = new javax.swing.JPanel();
        depsScroll = new javax.swing.JScrollPane();
        depsPanel = new javax.swing.JPanel();
        depsLabel = new javax.swing.JLabel();
        consolePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ApperyUnit");

        treePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Server Code");
        scriptsTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(scriptsTree);

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        paramsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ".params", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP));

        saveParamsButton.setText("Save");
        saveParamsButton.setActionCommand("");
        saveParamsButton.setEnabled(false);
        saveParamsButton.setPreferredSize(new java.awt.Dimension(100, 29));
        saveParamsButton.setSize(new java.awt.Dimension(100, 29));
        saveParamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveParamsButtonActionPerformed(evt);
            }
        });

        paramListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        paramListComboBox.setEnabled(false);

        newParamsButton.setText("New");
        newParamsButton.setEnabled(false);

        resetParamsButton.setText("Reset");
        resetParamsButton.setEnabled(false);
        resetParamsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetParamsButtonActionPerformed(evt);
            }
        });

        paramsSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        paramsSplitPane.setResizeWeight(0.5);

        paramsQueryArea.setEditable(false);
        paramsQueryArea.setColumns(20);
        paramsQueryArea.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        paramsQueryArea.setRows(5);
        paramsQueryArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paramsQueryAreaChanged(evt);
            }
        });
        paramsQueryScrollPane.setViewportView(paramsQueryArea);

        paramsSplitPane.setLeftComponent(paramsQueryScrollPane);

        paramsBodyArea.setColumns(20);
        paramsBodyArea.setRows(5);
        paramsBodyArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paramsBodyAreaChanged(evt);
            }
        });
        paramsBodyScrollPane.setViewportView(paramsBodyArea);

        paramsSplitPane.setRightComponent(paramsBodyScrollPane);

        javax.swing.GroupLayout paramsPanelLayout = new javax.swing.GroupLayout(paramsPanel);
        paramsPanel.setLayout(paramsPanelLayout);
        paramsPanelLayout.setHorizontalGroup(
            paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paramListComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newParamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveParamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetParamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(paramsSplitPane)
        );
        paramsPanelLayout.setVerticalGroup(
            paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paramsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paramsSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveParamsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newParamsButton)
                    .addComponent(resetParamsButton))
                .addContainerGap())
        );

        scriptNamePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scriptNameLabel.setText("Script name");

        javax.swing.GroupLayout scriptNamePanelLayout = new javax.swing.GroupLayout(scriptNamePanel);
        scriptNamePanel.setLayout(scriptNamePanelLayout);
        scriptNamePanelLayout.setHorizontalGroup(
            scriptNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scriptNameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        scriptNamePanelLayout.setVerticalGroup(
            scriptNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scriptNameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        runButton.setText("Run");
        runButton.setEnabled(false);
        runButton.setPreferredSize(new java.awt.Dimension(100, 29));
        runButton.setSize(new java.awt.Dimension(100, 29));
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        echoButton.setText("Echo");
        echoButton.setEnabled(false);
        echoButton.setPreferredSize(new java.awt.Dimension(100, 29));
        echoButton.setSize(new java.awt.Dimension(100, 29));
        echoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echoButtonActionPerformed(evt);
            }
        });

        testButton.setText("Test");
        testButton.setActionCommand("");
        testButton.setEnabled(false);
        testButton.setPreferredSize(new java.awt.Dimension(100, 29));
        testButton.setSize(new java.awt.Dimension(100, 29));
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        downloadButton.setText("Download");
        downloadButton.setEnabled(false);
        downloadButton.setPreferredSize(new java.awt.Dimension(100, 29));
        downloadButton.setSize(new java.awt.Dimension(100, 29));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.setActionCommand("");
        closeButton.setPreferredSize(new java.awt.Dimension(100, 29));
        closeButton.setSize(new java.awt.Dimension(100, 29));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(echoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(echoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dependenciesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP));

        javax.swing.GroupLayout depsPanelLayout = new javax.swing.GroupLayout(depsPanel);
        depsPanel.setLayout(depsPanelLayout);
        depsPanelLayout.setHorizontalGroup(
            depsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        depsPanelLayout.setVerticalGroup(
            depsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        depsScroll.setViewportView(depsPanel);

        depsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        depsLabel.setText("No dependencies");

        javax.swing.GroupLayout dependenciesPanelLayout = new javax.swing.GroupLayout(dependenciesPanel);
        dependenciesPanel.setLayout(dependenciesPanelLayout);
        dependenciesPanelLayout.setHorizontalGroup(
            dependenciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dependenciesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dependenciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(depsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dependenciesPanelLayout.setVerticalGroup(
            dependenciesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dependenciesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depsScroll)
                .addContainerGap())
        );

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(dependenciesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scriptNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scriptNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(dependenciesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        consolePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Console", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP));

        consoleArea.setEditable(false);
        consoleArea.setColumns(20);
        consoleArea.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        consoleArea.setRows(5);
        jScrollPane2.setViewportView(consoleArea);

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(treePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(treePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveParamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveParamsButtonActionPerformed
        appery.buttonSaveParams();
    }//GEN-LAST:event_saveParamsButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        appery.buttonDownload();
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        appery.buttonTest();
    }//GEN-LAST:event_testButtonActionPerformed

    private void echoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echoButtonActionPerformed
        appery.buttonEcho();
    }//GEN-LAST:event_echoButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        appery.buttonRun();
    }//GEN-LAST:event_runButtonActionPerformed

    private void paramsQueryAreaChanged(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paramsQueryAreaChanged
        saveParamsButton.setEnabled(true);
        resetParamsButton.setEnabled(true);
        runButton.setEnabled(false);
        echoButton.setEnabled(false);
        testButton.setEnabled(false);
    }//GEN-LAST:event_paramsQueryAreaChanged

    private void paramsBodyAreaChanged(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paramsBodyAreaChanged
        saveParamsButton.setEnabled(true);
        resetParamsButton.setEnabled(true);
        runButton.setEnabled(false);
        echoButton.setEnabled(false);
        testButton.setEnabled(false);
    }//GEN-LAST:event_paramsBodyAreaChanged

    private void resetParamsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetParamsButtonActionPerformed
        appery.buttonResetParams();
    }//GEN-LAST:event_resetParamsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea consoleArea;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel dependenciesPanel;
    private javax.swing.JLabel depsLabel;
    private javax.swing.JPanel depsPanel;
    private javax.swing.JScrollPane depsScroll;
    private javax.swing.JButton downloadButton;
    private javax.swing.JButton echoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newParamsButton;
    private javax.swing.JComboBox<String> paramListComboBox;
    private javax.swing.JTextArea paramsBodyArea;
    private javax.swing.JScrollPane paramsBodyScrollPane;
    private javax.swing.JPanel paramsPanel;
    private javax.swing.JTextArea paramsQueryArea;
    private javax.swing.JScrollPane paramsQueryScrollPane;
    private javax.swing.JSplitPane paramsSplitPane;
    private javax.swing.JButton resetParamsButton;
    private javax.swing.JButton runButton;
    private javax.swing.JButton saveParamsButton;
    private javax.swing.JLabel scriptNameLabel;
    private javax.swing.JPanel scriptNamePanel;
    private javax.swing.JTree scriptsTree;
    private javax.swing.JButton testButton;
    private javax.swing.JPanel treePanel;
    // End of variables declaration//GEN-END:variables
}
